# Generated by Django 3.2.11 on 2022-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceshi',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
