# Generated by Django 3.2.11 on 2022-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_building'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
