# Generated by Django 3.2.11 on 2022-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_delete_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('legal_person', models.TextField()),
                ('Contacts', models.TextField()),
                ('Phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('industry', models.TextField()),
                ('address', models.TextField()),
                ('scope', models.TextField()),
                ('label', models.TextField()),
                ('regis_time', models.TextField()),
                ('regis_capital', models.BigIntegerField()),
                ('credit_code', models.BigIntegerField()),
                ('tax_iden_number', models.CharField(max_length=255)),
                ('kind', models.TextField()),
                ('size', models.TextField()),
            ],
        ),
    ]
