# Generated by Django 3.2.11 on 2022-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jincheng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abbreviation', models.TextField()),
                ('author', models.TextField()),
                ('department', models.TextField()),
                ('release_source', models.TextField()),
                ('prefecture', models.TextField()),
                ('kind', models.TextField()),
                ('abstract', models.TextField()),
                ('details', models.TextField()),
                ('declares', models.TextField()),
                ('declare_start_time', models.TextField()),
                ('declare_end_time', models.TextField()),
                ('reward_description', models.TextField()),
                ('release_time', models.TextField()),
                ('key_words', models.TextField()),
                ('label', models.TextField()),
                ('subsidy_amount', models.IntegerField(max_length=11)),
            ],
        ),
    ]
