# Generated by Django 3.2.11 on 2022-01-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_jincheng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jincheng',
            old_name='prefecture',
            new_name='prefecture_city',
        ),
    ]
