# Generated by Django 3.2.11 on 2022-01-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_rename_prefecture_jincheng_prefecture_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jincheng',
        ),
    ]
