# Generated by Django 3.2.11 on 2022-01-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_jincheng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Jincheng',
        ),
    ]
