# Generated by Django 3.2.11 on 2022-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20220110_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('legal_person', models.TextField()),
                ('Contacts', models.TextField()),
                ('Phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('industry', models.TextField()),
                ('address', models.TextField()),
                ('scope', models.TextField()),
                ('label', models.TextField()),
                ('regis_time', models.TextField()),
                ('regis_capital', models.BigIntegerField()),
                ('credit_code', models.BigIntegerField()),
                ('tax_iden_number', models.CharField(max_length=255)),
                ('kind', models.TextField()),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jincheng',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abbreviation', models.TextField()),
                ('author', models.TextField()),
                ('department', models.TextField()),
                ('release_source', models.TextField()),
                ('prefecture_city', models.TextField()),
                ('kind', models.TextField()),
                ('abstract', models.TextField()),
                ('details', models.TextField()),
                ('declares', models.TextField()),
                ('declare_start_time', models.TextField()),
                ('declare_end_time', models.TextField()),
                ('reward_description', models.TextField()),
                ('release_time', models.TextField()),
                ('key_words', models.TextField()),
                ('label', models.TextField()),
                ('subsidy_amount', models.IntegerField(max_length=11)),
            ],
        ),
    ]
